name: beta_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  url_launcher: ^6.2.5
  video_player: ^2.8.6
  chewie: ^1.7.5 # Ditambahkan
  google_fonts: ^6.2.1
  intl: ^0.19.0 # Added for number formatting
  dio: ^5.9.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^14.2.0
  sizer: ^2.0.15
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/AMC/
    - assets/images/AMG/
    - assets/images/ATS/
    - assets/images/Abarth/
    - assets/images/Acura/
    - assets/images/Alfa/
    - assets/images/Alpine/
    - assets/images/Alumicraft/
    - assets/images/Apollo/
    - assets/images/Ariel/
    - assets/images/Ascari/
    - assets/images/Aston Martin/
    - assets/images/Audi/
    - assets/images/Austin-Healey/
    - assets/images/Auto/
    - assets/images/BAC/
    - assets/images/BMW/
    - assets/images/Bentley/
    - assets/images/Brabham/
    - assets/images/Bugatti/
    - assets/images/Buick/
    - assets/images/Cadillac/
    - assets/images/Chevrolet/
    - assets/images/Czinger/
    - assets/images/Datsun/
    - assets/images/DeBerti/
    - assets/images/Dodge/
    - assets/images/FIAT/
    - assets/images/Fast/
    - assets/images/Ferrari/
    - assets/images/Ford/
    - assets/images/Formula/
    - assets/images/Forsberg/
    - assets/images/GMC/
    - assets/images/Hennessey/
    - assets/images/Holden/
    - assets/images/Honda/
    - assets/images/Hoonigan/
    - assets/images/Hot Wheels/
    - assets/images/Hyundai/
    - assets/images/Jaguar/
    - assets/images/Jeep/
    - assets/images/KTM/
    - assets/images/Koenigsegg/
    - assets/images/Lamborghini/
    - assets/images/Lancia/
    - assets/images/Lexus/
    - assets/images/Lola/
    - assets/images/Lotus/
    - assets/images/MG/
    - assets/images/MINI/
    - assets/images/Maserati/
    - assets/images/Mazda/
    - assets/images/McLaren/
    - assets/images/Mercedes-Benz/
    - assets/images/Mercedes-AMG/
    - assets/images/Mercury/
    - assets/images/Meyers/
    - assets/images/Mitsubishi/
    - assets/images/Morgan/
    - assets/images/Mosler/
    - assets/images/Nissan/
    - assets/images/Oldsmobile/
    - assets/images/Pagani/
    - assets/images/Plymouth/
    - assets/images/Pontiac/
    - assets/images/Porsche/
    - assets/images/Radical/
    - assets/images/Renault/
    - assets/images/SIERRA/
    - assets/images/Saleen/
    - assets/images/Shelby/
    - assets/images/Subaru/
    - assets/images/Toyota/
    - assets/images/Ultima/
    - assets/images/Volkswagen/
    - assets/images/Volvo/
    - assets/videos/
    - assets/images/utility/
    - assets/images/profile/
